server:
  port: 8081
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
#    hibernate:
#      ddl-auto: create
  datasource:
    url: ${DB_URL}
#    url: jdbc:postgresql://localhost:5432/profiles
    username: profiles
    password: profiles